### ISSUE TITLE
dataset size?

### ISSUE THREAD

**Issue by andrebeu** [notnews/nbc_transcripts#1]
awesome work!

I'm currently on the hunt for large amounts of text data from news sources like fox news, cbs, etc... 
Do you have an estimate word count for how much you are getting from NBC?

Thanks for sharing!
Andre

**Comment by soodoku** [comment]
Thanks!

1. Re. word count: Here's my top of the head calculation. Transcripts = 5k. Each transcript can be pretty long ~ 7k+ words. Multiply the 2. Data are posted and it won't take you more than 2 min. to figure this out.

2. You may also like my repo. on cnn_transcripts.

**Comment by andrebeu** [comment]
Thanks again!!
